# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30e38fcd30b7b99e95718de9df8d6d1c842edd9a93e693ab8ec231cc2fe01661bbad6bc2e0ba27bd85e07068227bda900916b40f482e277837f299b00332f32

test:
  secret_key_base: d2377d45eb6c3fa79a85345a138f001ab17c14c9c83713ed55d84d66c6906d6ee13abcb2a43afc365242a59d9dc9c3ec9cefd290fdee619d97c73b83d8ac6eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
